### ISSUE TITLE
CI-CD

### ISSUE THREAD

**Issue by bartr** [bartr/bluebell#20]
### Build and publish Integration Test container as part of CI-CD

CI-CD currently builds and publishes the app. Should we also build and publish the integration test? If so, should that be a separate yml file or part of the master build?

If separate, we could trigger on /src/integration-test and only run when the code changes

**Comment by aflinchb** [comment]
I like the idea of adding it as separate pipeline (and separate yml file) in the same project.  We should also consider adding instructions to the readme to run the integration tests by building and running the docker image.  I'm assuming that will be the recommended approach long-term since that way it can be run on node/java without having to have dotnet set up.

**Comment by bartr** [comment]
Fixed in PR #54
